const get = (req,res) =>{
    res.send([
        {
            "id": "11",
            "title": "Top Gun Maverick BO: Tom Cruise film collects $51 mn in US, ₹4.75 cr in India ",
            "Image": "https://images.hindustantimes.com/img/2022/05/28/550x309/dcf35a88-dd9e-11ec-8fe2-ac5ac3115257_1653667000472_1653747840857.jpg",
            "category": "Hollywood",
            "description": "Top Gun Maverick box office day 1 collection: Tom Cruise's film collected $51 million at the US box office on its opening day. In India, it collected ₹4.75 crore. Top Gun came out in 1986, establishing Cruise, then 24, as an action hero. He’s nearly 60 now, promoted to US Navy captain in the sequel, and working hard to recreate the magic from 36 years ago.Director Joseph Kosinski's Top Gun Maverick, which features Tom Cruise, had a contrasting opening at the box office in India and the US. In the US, the film collected $51 million on its opening day. The film is already Tom’s best opening day ever beating Mission Impossible – Fallout's first-day collection. However, the film has not been able to make a mark in India and collected ₹4.75 crore on day one. In Top Gun Maverick, Tom essays the role of Pete 'Maverick' Mitchell, who is grappling with the diminished standing of fighter pilots in a world that now wages war with drones controlled by people miles away on computers. Top Gun Maverick is produced by Jerry Bruckheimer, Tom Cruise, Christopher McQuarrie and David Ellison.As per a Deadline report, Top Gun Maverick at this Friday night hour is on its way to a $51 million opening day (which includes $19.3 million previews). It would not be shocking to wake up on Saturday morning and see that the sequel has edged out Iron Man 2 ($51.2M) to become Paramount’s top opening day ever. Already, the sequel is Tom Cruise’s best opening day ever in US/Canada besting Mission: Impossible – Fallout‘s first day of $22.8M by 124%."
          },
          {
            "id": "55",
            "title": "Top Gun Maverick BO: Tom Cruise film collects $51 mn in US, ₹4.75 cr in India ",
            "Image": "https://images.hindustantimes.com/img/2022/05/28/550x309/dcf35a88-dd9e-11ec-8fe2-ac5ac3115257_1653667000472_1653747840857.jpg",
            "category": "mix",
            "description": "Top Gun Maverick box office day 1 collection: Tom Cruise's film collected $51 million at the US box office on its opening day. In India, it collected ₹4.75 crore. Top Gun came out in 1986, establishing Cruise, then 24, as an action hero. He’s nearly 60 now, promoted to US Navy captain in the sequel, and working hard to recreate the magic from 36 years ago.Director Joseph Kosinski's Top Gun Maverick, which features Tom Cruise, had a contrasting opening at the box office in India and the US. In the US, the film collected $51 million on its opening day. The film is already Tom’s best opening day ever beating Mission Impossible – Fallout's first-day collection. However, the film has not been able to make a mark in India and collected ₹4.75 crore on day one. In Top Gun Maverick, Tom essays the role of Pete 'Maverick' Mitchell, who is grappling with the diminished standing of fighter pilots in a world that now wages war with drones controlled by people miles away on computers. Top Gun Maverick is produced by Jerry Bruckheimer, Tom Cruise, Christopher McQuarrie and David Ellison.As per a Deadline report, Top Gun Maverick at this Friday night hour is on its way to a $51 million opening day (which includes $19.3 million previews). It would not be shocking to wake up on Saturday morning and see that the sequel has edged out Iron Man 2 ($51.2M) to become Paramount’s top opening day ever. Already, the sequel is Tom Cruise’s best opening day ever in US/Canada besting Mission: Impossible – Fallout‘s first day of $22.8M by 124%."
          },
          {
            "id": "12",
            "title": " Amber Heard-Johnny Depp trial: Elon Musk says he hopes 'they both move on’ ",
            "Image": "https://images.hindustantimes.com/img/2022/05/28/550x309/Johnny_Depp-amber_heard_1653737448892_1653737458747.jfif",
            "category": "Hollywood",
            "description": "Responding to a tweet on Johnny and Amber Heard's trial, Elon wrote on Twitter, I hope they both move on. At their best, they are each incredible. He was reacting to a tweet by MIT Research Scientist Lex Fridman. Lex had written, My takeaways from Johnny Depp vs Amber Heard trial: 1. Fame is one hell of a drug (for some). 2. Psychiatrists & lawyers come in drastically varying levels of skill. 3. Lying to millions of people is something humans are capable of. 4. Love can be messy. 5. Mega pint of wine.Johnny has sued Amber in Virginia for $50 million and argued that she defamed him when she called herself a public figure representing domestic abuse in an opinion piece she wrote. Amber countersued for $100 million, saying he smeared her when his lawyer called her accusations a hoax.A seven-person jury deliberated for more than two hours on Friday and will resume discussions on Tuesday. At the centre of the legal case is the December 2018 opinion piece by Amber in the Washington Post, in which she made the statement about domestic abuse. The article never mentioned Johnny by name, but his lawyer told jurors it was clear that she was referring to him"
          },
          {
            "id": "13",
            "title": "Amber Heard says she has received threats 'every single day' during trial: 'People want to put my baby in a microwave' ",
            "Image": "https://images.hindustantimes.com/img/2022/05/27/550x309/amber_heard_1652846124301_1653656835956.JPG",
            "category": "Hollywood",
            "description": "In a video from the trial shared by Law & Crime Network on their YouTube channel, Amber told the jury, I am harassed, humiliated, threatened, every single day. Even just walking into this courtroom. Sitting here in front of the world, having the worst parts of my life, things that I have lived through, used to humiliate me. People want to kill me and they tell me so every day. People want to put my baby in the microwave, and they tell me that. She also said, I live my life with these sets of rules I've to follow, my friends have to follow for me not to have a panic attack or a triggering event or I relive the trauma, even from training to do. In my movie, for instance, for training for Aquaman, a combat scene and a trigger happen. I have a meltdown and have to deal with that, the crew I work with have to deal with that, because of the damage I walk around with every single day. I am not sitting in this courtroom snickering. I’m not sitting in this courtroom laughing, smiling, or making snide jokes. I’m not. This is horrible. A jury is scheduled to hear the closing arguments on Friday in Johnny's lawsuit against Amber. Each side will have two hours to summarise their case in a trial that has stretched on for six weeks. Johnny Depp is suing Amber for $50 million in Virginia's Fairfax County Circuit Court over a December 2018 op-ed she wrote in The Washington Post describing herself as “a public figure representing domestic abuse”. His lawyers say he was defamed by the article even though it never mentioned his name."
          },
          {
            "id": "62",
            "title": "Amber Heard says she has received threats 'every single day' during trial: 'People want to put my baby in a microwave' ",
            "Image": "https://images.hindustantimes.com/img/2022/05/27/550x309/amber_heard_1652846124301_1653656835956.JPG",
            "category": "footer2",
            "description": "In a video from the trial shared by Law & Crime Network on their YouTube channel, Amber told the jury, I am harassed, humiliated, threatened, every single day. Even just walking into this courtroom. Sitting here in front of the world, having the worst parts of my life, things that I have lived through, used to humiliate me. People want to kill me and they tell me so every day. People want to put my baby in the microwave, and they tell me that. She also said, I live my life with these sets of rules I've to follow, my friends have to follow for me not to have a panic attack or a triggering event or I relive the trauma, even from training to do. In my movie, for instance, for training for Aquaman, a combat scene and a trigger happen. I have a meltdown and have to deal with that, the crew I work with have to deal with that, because of the damage I walk around with every single day. I am not sitting in this courtroom snickering. I’m not sitting in this courtroom laughing, smiling, or making snide jokes. I’m not. This is horrible. A jury is scheduled to hear the closing arguments on Friday in Johnny's lawsuit against Amber. Each side will have two hours to summarise their case in a trial that has stretched on for six weeks. Johnny Depp is suing Amber for $50 million in Virginia's Fairfax County Circuit Court over a December 2018 op-ed she wrote in The Washington Post describing herself as “a public figure representing domestic abuse”. His lawyers say he was defamed by the article even though it never mentioned his name."
          },
          {
            "id": "14",
            "title": "Gauri Khan praises Manish Malhotra for making her look 'so slim', says Maheep Kapoor 'firing me even while posing' ",
            "Image": "https://images.hindustantimes.com/img/2022/05/28/550x309/gauri-khan_1653743810258_1653743890064.jfif",
            "category": "Hollywood",
            "description": "In the first picture she posted on Instagram, Gauri sat on a bar stool as she posed sideways for the camera. She faced the lens in the second photo. Gauri gave another pose in the last picture. She captioned the post, Wow !!! You’ve made me look so slim and tagged Manish Malhotra. Reacting to the post, Manish dropped red heart emojis and Maheep added fire, heart eyes and heart emojis. Ananya Panday wrote, Love it. Namrata Shirodkar and Shanaya Kapoor posted heart eyes emojis. Malaika Arora commented, Awesome G. On her Instagram Stories, Gauri also shared a clip in which she seemingly tried to hold Maheep's hand as they posed for the photos at Karan's birthday venue. As Maheep quickly turned and told her something, Gauri made a face, laughed and looked at her."
          },
          {
            "id": "15",
            "title": "Elon Musk to borrow less in Twitter bid, filing says ",
            "Image": "https://images.hindustantimes.com/img/2022/05/26/550x309/TWITTER-AGM-0_1653534087051_1653534101559.JPG",
            "category": "Hollywood",
            "description": "Tesla CEO Elon Musk has been courting major Twitter investors including co-founder Jack Dorsey in the hope of getting them to partner with him in taking the San Francisco-based company private.Elon Musk notified US regulators on Wednesday that he will rely less on loans in his bid to buy Twitter, as he and partners put $33.5 billion into the deal.Twitter shares climbed more than 5 percent on the news, as the market evidently took it as a sign the acquisition is moving forward despite Musk declaring it on hold due to his concerns about the number of accounts that might be software bots instead of real people. Musk said in the regulatory filing that he had new commitments that will allow him to rely less on loans to buy Twitter, but did not specify whether he was reaching into his own pocket for money or had won over others with big stakes in the company Analysts were concerned about Musk using billions of dollars worth of his Tesla shares to back loans, meaning the electric car company's stock price would be affected by the fortunes of Twitter  ."
          },
          {
            "id": "16",
            "title": "Explained: Will Amber Heard or Johnny Depp go to prison if other party wins? ",
            "Image": "https://images.hindustantimes.com/img/2022/05/29/550x309/Amber_Johnny_1653803672420_1653803684854.jpeg",
            "category": "Hollywood",
            "description": "ohnny Depp and Amber Heard’s bitter and public defamation trial came to a close on Friday as both parties rested their case, and the judge handed the case over to the jury. Now, the jury will deliberate over the case’s facts and findings and deliver their verdict next week. The high-profile defamation trial has seen its fair share of twists and turns. But now the question on everyone’s lips is what would be the outcome. As per reports, Johnny Depp is heavily favoured to emerge victorious in his suit against his ex-wife. But if he does win, what does that mean for Amber? We take a look.Johnny has sued Amber for $50 million saying she defamed him when she claimed to be a victim of domestic violence in a Washington Post op-ed in 2018. Johnny’s lawyers have said that even though Amber didn’t name him, the implication damaged his career. He has further alleged that Amber was abusive towards him during their marriage. Amber has countersued him for $100 million claiming that he has smeared her name by calling her a liar. She has maintained that she suffered physical and sexual abuse at Johnny’s hands. Both trials ran concurrently in a Virginia court for over six weeks. The hearings ended on May 27."
          },
          {
            "id": "17",
            "title": "Cannes full list of winners: Swedish film Triangle of Sadness wins Palme d'Or ",
            "Image": "https://images.hindustantimes.com/img/2022/05/29/550x309/FILMFESTIVAL-CANNES-AWARDS-354_1653794715337_1653794733888.JPG",
            "category": "Hollywood",
            "description": "The 75th Cannes Film Festival - Closing ceremony - Cannes, France, May 28, 2022. Song Kang-ho, Best Actor award winner for his role in the film Broker (Les bonnes etoiles), director Ruben Ostlund, Palme d'Or award winner for the film film Triangle of Sadness, and Vincent Lindon, Jury President of the 75th Cannes Film Festival, react on stage. REUTERS/Sarah Meyssonnier TPX IMAGES OF THE DAY(REUTERS). The 75th edition of the Cannes Film Festival came to a glittering close on Saturday with the nine-member jury giving out the big awards at the prestigious festival. Swedish director Ruben Ostlund’s class warfare comedy took the top honours by winning the festival's top prize--the Palme d’Or. Korean cinema again showed its dominance by taking home multiple awards for different films.The awards were selected by a nine-member jury headed by French actor Vincent Lindon and presented Saturday in a closing ceremony inside Cannes' Grand Lumière Theater. The jury included an Indian face in actor Deepika Padukone. A separate section of two awards for documentary films was adjudged e earlier on Saturday. Those awards were adjudged by a separate jury."
          },
          {
            "id": "18",
            "title": "Goodfellas actor Ray Liotta dies at 67: media reports ",
            "Image": "https://images.hindustantimes.com/img/2022/05/26/550x309/_850bdaac-499d-11e6-90e0-482a513bad8b_1653583341724.jpg",
            "category": "Hollywood",
            "description": "Actor Ray Liotta, star of the gangster film Goodfellas, has died at the age of 67 in Dominican Republic, as per media reports.Ray was engaged to be married to Jacy Nittolo and leaves behind a daughter, Yahoo reported. He was in the Dominican Republic shooting the film Dangerous Waters, as per a report in Deadline. The report also added that the actor died in his sleep on Thursday.While Ray was best known for his role in Martin Scorsese's Goodfellas, he had performed in a number of other films over the years, most notably Field of Dreams. He was on a path of resurgence in recent years with increased visibility and roles in major films. His recent roles included The Many Saints of Newark, Marriage Story and No Sudden Move.Deadline reported that he had finished the Elizabeth Banks-directed Cocaine Bear and was also due to star in the Working Title film The Substance opposite Demi Moore and Margaret Qualley."
          },
          {
            "id": "19",
            "title": "Jake Gyllenhaal: Acting is not real life in any form, you walk into a scene with all of your life experiences ",
            "Image": "https://images.hindustantimes.com/img/2022/05/28/550x309/US-CLOSING-ARGUMENTS-BEGIN-IN-DEPP-V--HEARD-TRIAL-5_1653726305859_1653726337385.jpg",
            "category": "Hollywood",
            "description": "Hollywood actor Jake Gyllenhaal took a conscious decision to stay in New York, but he admits his soul is in Los Angeles.For a lot of people, real life is deeply connected with the acting world, and sometimes even mirrors it, but that doesn’t stand true for Hollywood star Jake Gyllenhaal.I think real life shapes you as a human, and acting shapes your imagination. I strongly believe that acting is not real life in any form,” Gyllenhaal tells us.It’s been over three decades since Gyllenhaal has been working his way through in Hollywood, bringing different shades of complicated men on screen from cons to police officers. He is known for films such as Donnie Darko, Brokeback Mountain, Zodiac, Nightcrawler, Spider-Man: Far from Home, The Guilty and Ambulance.Opening up about his method as an actor, the 41-year-old shares, “A lot of times people say that acting is pretend. I don’t believe acting is pretend. I think it’s a real access to your imagination and a sense of play. And then you can hopefully build the human you are with the stuff that has nothing to do with the acting, but more to do with life and the people you love and the things you go through good and bad”"
          },
          {
            "id": "20",
            "title": "op Gun 2 tipped to be Tom Cruise’s career-best opener with $125 million weekend ",
            "Image": "https://images.hindustantimes.com/img/2022/05/25/550x309/_569e90dc-cd70-11ea-a892-bc0febb83d85_1653488101945.jpg",
            "category": "Hollywood",
            "description": "Tom Cruise's Top Gun Maverick has been projected to earn $125 million in its opening weekend, which will comfortably make it he best opener in the actor's long career.As per trade reports, Tom Cruise’s upcoming film Top Gun: Maverick could end up registering the biggest opening by any film of his career. Despite his stardom, Tom has never had a film gross over $100 million on the opening weekend. But reports say that Maverick may just change that. Some estimates claim that the film could end up making $125 million in its opening weekend in the domestic market alone.According to a report in The Hollywood Reporter, “Top Gun 2 is easily headed for the biggest opening of Tom Cruise’s career at the domestic box office, with a four-day gross of at least $92 million, according to official tracking. And that’s a conservative estimate. Many pundits believe the critically acclaimed sequel could soar well north of $100 million domestically, but tracking — one of Hollywood’s favorite pastimes — has become fraught in the pandemic era. Exhibitors are especially bullish on the pic, and are even thinking $125 million-plus.”"
          }
    ])
}
module.exports.apiController = get;